/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilandatabase;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SHOFYYAH
 */
public class TampilanGUI extends javax.swing.JFrame {
    
    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Karyawan> dataKaryawan;

    private int masukkanData(Connection conn, String id_karyawan, String nama, String alamat) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("INSERT INTO identitas (id_karyawan,nama,alamat) VALUES(?,?,?)");
        pst.setString(1, id_karyawan);
        pst.setString(2, nama);
        pst.setString(3, alamat);
        return pst.executeUpdate();
    }
    
    private int perbaruiData(Connection conn, String id_karyawan, String nama, String alamat) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("UPDATE identitas SET nama=?, alamat=? WHERE id_karyawan=?");
        pst.setString(1, nama);
        pst.setString(2, alamat);
        pst.setString(3, id_karyawan);
        return pst.executeUpdate();
    }

    private int hapusData(Connection conn, String id_karyawan) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("DELETE FROM identitas WHERE id_karyawan=?");
        pst.setString(1, id_karyawan);
        return pst.executeUpdate();
    }


    private void tampil(Connection conn) {
        dataKaryawan.clear();
        try {
            String sql = "select * from identitas";
            Statement st = (Statement) conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Karyawan data = new Karyawan();
                data.setId_karyawan(String.valueOf(rs.getObject(1)));
                data.setNama(String.valueOf(rs.getObject(2)));
                data.setAlamat(String.valueOf(rs.getObject(3)));
                dataKaryawan.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableKaryawan.getModel();
            model.setRowCount(0);
            for (Karyawan data : dataKaryawan) {

                Object[] baris = new Object[3];
                baris[0] = data.getId_karyawan();
                baris[1] = data.getNama();
                baris[2] = data.getAlamat();

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TampilanGUI
     */
    public TampilanGUI() {
        try {
            dataKaryawan = new ArrayList<>();
            initComponents();
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/karyawan", "postgres", "1234");
            tampil(conn);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNama = new javax.swing.JLabel();
        jLabelIdKaryawan = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldIdKaryawan = new javax.swing.JTextField();
        jScrollPaneTableKaryawan = new javax.swing.JScrollPane();
        jTableKaryawan = new javax.swing.JTable();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jLabelAlamat = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabelDataKaryawan = new javax.swing.JLabel();
        jButtonCetak = new javax.swing.JButton();
        jLabelDataKaryawan1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNama.setText("Nama");
        getContentPane().add(jLabelNama);
        jLabelNama.setBounds(60, 230, 40, 20);

        jLabelIdKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelIdKaryawan.setText("Id Karyawan");
        getContentPane().add(jLabelIdKaryawan);
        jLabelIdKaryawan.setBounds(20, 190, 90, 20);

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(120, 230, 137, 22);

        jTextFieldIdKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdKaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdKaryawan);
        jTextFieldIdKaryawan.setBounds(120, 190, 137, 22);

        jTableKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Karyawan", "Nama", "Alamat"
            }
        ));
        jTableKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKaryawanMouseClicked(evt);
            }
        });
        jScrollPaneTableKaryawan.setViewportView(jTableKaryawan);

        getContentPane().add(jScrollPaneTableKaryawan);
        jScrollPaneTableKaryawan.setBounds(300, 180, 270, 250);

        jButtonSimpan.setBackground(new java.awt.Color(255, 255, 204));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan);
        jButtonSimpan.setBounds(40, 370, 72, 23);

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate);
        jButtonUpdate.setBounds(120, 370, 72, 23);

        jButtonHapus.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus);
        jButtonHapus.setBounds(200, 370, 72, 23);

        jLabelAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAlamat.setText("Alamat");
        getContentPane().add(jLabelAlamat);
        jLabelAlamat.setBounds(50, 270, 50, 16);

        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAlamat);
        jTextFieldAlamat.setBounds(120, 270, 160, 22);

        jLabelDataKaryawan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataKaryawan.setText("DATA KARYAWAN ");
        getContentPane().add(jLabelDataKaryawan);
        jLabelDataKaryawan.setBounds(220, 72, 180, 20);

        jButtonCetak.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak);
        jButtonCetak.setBounds(40, 400, 228, 23);

        jLabelDataKaryawan1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabelDataKaryawan1.setText("PT MERDEKA JAYA ");
        getContentPane().add(jLabelDataKaryawan1);
        jLabelDataKaryawan1.setBounds(170, 90, 300, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHOFYYAH\\Downloads\\12345.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 591, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String id_karyawan = jTextFieldIdKaryawan.getText().trim();
        String nama = jTextFieldNama.getText();
        String alamat = jTextFieldAlamat.getText();
        if (!id_karyawan.isEmpty() && !nama.isEmpty() && !alamat.isEmpty()) {

            try {
                // TODO add your handling code here:
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/karyawan", "postgres", "1234");
                int k = masukkanData(conn, id_karyawan, nama, alamat);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Karyawan Gagal");
        }
        jTextFieldAlamat.setText("");
        jTextFieldIdKaryawan.setText("");
        jTextFieldNama.setText("");

    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
                                             
    String id_karyawan = jTextFieldIdKaryawan.getText().trim();
    String nama = jTextFieldNama.getText();
    String alamat = jTextFieldAlamat.getText();
    
    if (!id_karyawan.isEmpty() && !nama.isEmpty() && !alamat.isEmpty()) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/karyawan", "postgres", "1234");
            int k = perbaruiData(conn, id_karyawan, nama, alamat); // Menggunakan perbaruiData
            if (k > 0) {
                tampil(conn);
                this.peringatan("Perbarui Berhasil");
            } else {
                this.peringatan("Perbarui Gagal");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        this.peringatan("Input Data Karyawan Gagal");
    }
    jTextFieldAlamat.setText("");
    jTextFieldIdKaryawan.setText("");
    jTextFieldNama.setText("");


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:                                           
    String id_karyawan = jTextFieldIdKaryawan.getText().trim();

    if (!id_karyawan.isEmpty()) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/karyawan", "postgres", "1234");
            int k = hapusData(conn, id_karyawan); // Menggunakan hapusData
            if (k > 0) {
                tampil(conn);
                this.peringatan("Hapus Berhasil");
            } else {
                this.peringatan("Hapus Gagal");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        this.peringatan("Input ID Karyawan Gagal");
    }
    jTextFieldAlamat.setText("");
    jTextFieldIdKaryawan.setText("");
    jTextFieldNama.setText("");

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jTextFieldIdKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdKaryawanActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTableKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKaryawanMouseClicked
        // TODO add your handling code here:

        int baris = jTableKaryawan.rowAtPoint(evt.getPoint());

        String id_karyawan = jTableKaryawan.getValueAt(baris, 0).toString();
        jTextFieldIdKaryawan.setText(id_karyawan);

        String nama = jTableKaryawan.getValueAt(baris, 1).toString();
        jTextFieldNama.setText(nama);

        String alamat = jTableKaryawan.getValueAt(baris, 2).toString();
        jTextFieldAlamat.setText(alamat);
    
    }//GEN-LAST:event_jTableKaryawanMouseClicked

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/karyawan", "postgres", "1234");

            //File jasperFile = new File("src/pbopertemuan6/mahasiswa.jasper");
            // JasperPrint jp = JasperFillManager.fillReport(jasperFile.getPath(), null, conn);
            String jrxmlFile = new String("src/tampilandatabase/reportKaryawan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCetakActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelDataKaryawan;
    private javax.swing.JLabel jLabelDataKaryawan1;
    private javax.swing.JLabel jLabelIdKaryawan;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JScrollPane jScrollPaneTableKaryawan;
    private javax.swing.JTable jTableKaryawan;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldIdKaryawan;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables

}
