/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buku;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SHOFYYAH
 */
public class Tampilan extends javax.swing.JFrame {
    
    private Timer refreshTimer;

public Tampilan() {
    try {
        dataBuku = new ArrayList<>();
        initComponents();
        Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Buku", "postgres", "1234");
        tampil(conn);

        // Membuat dan mengatur timer untuk auto-refresh setiap 5 detik (5000 milidetik)
        refreshTimer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tampil(conn);
            }
        });
        refreshTimer.start();
    } catch (SQLException ex) {
        Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Buku> dataBuku;

    private int masukkanData(Connection conn, String isbn, String judul_buku, String tahun_terbit, String penerbit) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("INSERT INTO buku (isbn,judul_buku,tahun_terbit,penerbit) VALUES(?,?,?,?)");
        pst.setString(1, isbn);
        pst.setString(2, judul_buku);
        pst.setString(3, tahun_terbit);
        pst.setString(4, penerbit);
        return pst.executeUpdate();
    }
    
    private int perbaruiData(Connection conn, String isbn, String judul_buku, String tahun_terbit, String penerbit) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("UPDATE buku SET judul_buku=?, tahun_terbit=?, penerbit=? WHERE isbn=?");
        pst.setString(4, isbn);
        pst.setString(1, judul_buku);
        pst.setString(2, tahun_terbit);
        pst.setString(3, penerbit);
        return pst.executeUpdate();
    }

    private int hapusData(Connection conn, String isbn) throws SQLException {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement("DELETE FROM buku WHERE isbn=?");
        pst.setString(1, isbn);
        return pst.executeUpdate();
    }
    
    private void tampil(Connection conn) {
        dataBuku.clear();
        try {
            String sql = "select * from buku";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Buku data = new Buku();
                data.setISBN(String.valueOf(rs.getObject(1)));
                data.setJudul_Buku(String.valueOf(rs.getObject(2)));
                data.setTahun_Terbit(String.valueOf(rs.getObject(3)));
                data.setPenerbit(String.valueOf(rs.getObject(4)));
                dataBuku.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTabledataBuku.getModel();
            model.setRowCount(0);
            for (Buku data : dataBuku) {

                Object[] baris = new Object[4];
                baris[0] = data.getISBN();
                baris[1] = data.getJudul_Buku();
                baris[2] = data.getTahun_Terbit();
                baris[3] = data.getPenerbit();
                

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelKoleksiPerpus = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jLabelJudulBuku = new javax.swing.JLabel();
        jLabelTahunTerbit = new javax.swing.JLabel();
        jLabelPenerbit = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jTextFieldJudulBuku = new javax.swing.JTextField();
        jTextFieldTahunTerbit = new javax.swing.JTextField();
        jTextFieldPenerbit = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledataBuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelKoleksiPerpus.setBackground(new java.awt.Color(255, 255, 204));
        jLabelKoleksiPerpus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelKoleksiPerpus.setText("KOLEKSI PERPUSTAKAAN MINI CACA");
        getContentPane().add(jLabelKoleksiPerpus);
        jLabelKoleksiPerpus.setBounds(320, 30, 440, 20);

        jLabelISBN.setBackground(new java.awt.Color(255, 255, 204));
        jLabelISBN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelISBN.setText("ISBN");
        getContentPane().add(jLabelISBN);
        jLabelISBN.setBounds(110, 90, 50, 25);

        jLabelJudulBuku.setBackground(new java.awt.Color(255, 255, 204));
        jLabelJudulBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJudulBuku.setText("Judul Buku");
        getContentPane().add(jLabelJudulBuku);
        jLabelJudulBuku.setBounds(60, 130, 100, 25);

        jLabelTahunTerbit.setBackground(new java.awt.Color(255, 255, 204));
        jLabelTahunTerbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTahunTerbit.setText("Tahun Terbit");
        getContentPane().add(jLabelTahunTerbit);
        jLabelTahunTerbit.setBounds(40, 170, 120, 25);

        jLabelPenerbit.setBackground(new java.awt.Color(255, 255, 204));
        jLabelPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPenerbit.setText("Penerbit");
        getContentPane().add(jLabelPenerbit);
        jLabelPenerbit.setBounds(80, 210, 80, 25);

        jTextFieldISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISBNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldISBN);
        jTextFieldISBN.setBounds(200, 90, 114, 22);

        jTextFieldJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJudulBukuActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJudulBuku);
        jTextFieldJudulBuku.setBounds(200, 130, 200, 22);

        jTextFieldTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTahunTerbitActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTahunTerbit);
        jTextFieldTahunTerbit.setBounds(200, 170, 85, 22);

        jTextFieldPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenerbitActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPenerbit);
        jTextFieldPenerbit.setBounds(200, 210, 161, 22);

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan);
        jButtonSimpan.setBounds(133, 373, 72, 23);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate);
        jButtonUpdate.setBounds(217, 373, 72, 23);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus);
        jButtonHapus.setBounds(301, 373, 72, 23);

        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak);
        jButtonCetak.setBounds(133, 408, 240, 30);

        jTabledataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Judul Buku", "Tahun Terbit", "Penerbit"
            }
        ));
        jTabledataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledataBuku);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(577, 90, 452, 270);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 24, 37, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISBNActionPerformed

    private void jTextFieldJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJudulBukuActionPerformed

    private void jTextFieldTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTahunTerbitActionPerformed

    private void jTextFieldPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenerbitActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
    String ISBN = jTextFieldISBN.getText().trim();

        if (!ISBN.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Buku", "postgres", "1234");
                int k = hapusData(conn, ISBN);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Hapus Berhasil");
                } else {
                    this.peringatan("Hapus Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Hapus Data Gagal");
        }
        
    jTextFieldISBN.setText("");
    jTextFieldJudulBuku.setText("");
    jTextFieldTahunTerbit.setText("");
    jTextFieldPenerbit.setText("");

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
           Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Buku", "postgres", "1234");


            String jrxmlFile = new String("src/buku/reportBuku.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
            
        } catch (JRException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            
        }catch (SQLException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);}
    
        
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String ISBN = jTextFieldISBN.getText().trim();
        String Judul_Buku = jTextFieldJudulBuku.getText();
        String Tahun_Terbit = jTextFieldTahunTerbit.getText();
        String Penerbit = jTextFieldPenerbit.getText();

        if (!ISBN.isEmpty() && !Judul_Buku.isEmpty() && !Tahun_Terbit.isEmpty() && !Penerbit.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Buku", "postgres", "1234");
                int k = masukkanData(conn, ISBN, Judul_Buku, Tahun_Terbit, Penerbit);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Gagal");
        }

        jTextFieldISBN.setText("");
        jTextFieldJudulBuku.setText("");
        jTextFieldTahunTerbit.setText("");
        jTextFieldPenerbit.setText("");
        
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
    String ISBN = jTextFieldISBN.getText().trim();
    String Judul_Buku = jTextFieldJudulBuku.getText();
    String Tahun_Terbit = jTextFieldTahunTerbit.getText();
    String Penerbit = jTextFieldPenerbit.getText();

        if (!ISBN.isEmpty() && !Judul_Buku.isEmpty() && !Tahun_Terbit.isEmpty() && !Penerbit.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Buku", "postgres", "1234");
                int k = perbaruiData(conn, ISBN, Judul_Buku, Tahun_Terbit, Penerbit);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Update Berhasil");
                } else {
                    this.peringatan("Update Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Update Data Gagal");
        }

    jTextFieldISBN.setText("");
    jTextFieldJudulBuku.setText("");
    jTextFieldTahunTerbit.setText("");
    jTextFieldPenerbit.setText("");

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTabledataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledataBukuMouseClicked
        // TODO add your handling code here:
        int baris = jTabledataBuku.rowAtPoint(evt.getPoint());

        String ISBN = jTabledataBuku.getValueAt(baris, 0).toString();
        jTextFieldISBN.setText(ISBN);

        String JudulBuku = jTabledataBuku.getValueAt(baris, 1).toString();
        jTextFieldJudulBuku.setText(JudulBuku);

        String TahunTerbit = jTabledataBuku.getValueAt(baris, 2).toString();
        jTextFieldTahunTerbit.setText(TahunTerbit);
        
        String Penerbit = jTabledataBuku.getValueAt(baris, 3).toString();
        jTextFieldPenerbit.setText(Penerbit);
    }//GEN-LAST:event_jTabledataBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelJudulBuku;
    private javax.swing.JLabel jLabelKoleksiPerpus;
    private javax.swing.JLabel jLabelPenerbit;
    private javax.swing.JLabel jLabelTahunTerbit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledataBuku;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldJudulBuku;
    private javax.swing.JTextField jTextFieldPenerbit;
    private javax.swing.JTextField jTextFieldTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
